// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otvsmmxosyiyuzczhycv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90dnNtbXhvc3lpeXV6Y3poeWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODAxMTEsImV4cCI6MjA2NTY1NjExMX0.8LHZit8t_VPVvwTfJ6NzKUEbrghb4QG4iKYkamjileI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);